loungeman/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'loungeman'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^helm(?P<user_id>[^/]+)/$', views.helm, name='helm'),
    url(r'^r/(?P<room_id>[^/]+)/$', views.room_view, name='room'),
    url(r'^r/(?P<room_id>[^/]+)/u/(?P<user_id>[^/]+)/$', views.room_view, name='room_user'),
    url(r'^r/(?P<room_id>[^/]+)/addeduser/$', views.adding_user, name='added'),
    url(r'^addroom/$', views.adding_room, name='addedroom'),
    url(r'^removeroom/(?P<room_id>[^/]+)/$', views.removing_room, name='removedroom'),
    url(r'^delroom/(?P<room_id>[^/]+)/u/(?P<user_id>[^/]+)/$', views.owner_delete_room, name='delroom'),
    url(r'^r/(?P<room_id>[^/]+)/qr/$', views.get_qr, name='getqr'),
    url(r'^r/(?P<room_id>[^/]+)/u/(?P<user_id>[^/]+)/qr/$', views.get_qr, name='getqr'),
    url(r'^r/(?P<room_id>[^/]+)/sendqr/$', views.send_qr, name='sendqr_room'),
    url(r'^r/(?P<room_id>[^/]+)/u/(?P<user_id>[^/]+)/sendqr/$', views.send_qr, name='sendqr_user'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loungeon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('loungeman.urls')),
    path('admin/', admin.site.urls),
]

loungeman/models.py
import string
import qrcode
from django.db import models
from numpy import random
import os
from django.conf import settings

# Constants
ID_LEN = 40
ID_CHARS = list(string.ascii_letters + string.digits)
COM_SEP = '/'
COM_UC = ':'
URL_IP = 'http://www.loungeon.com'
URL_ROOM = URL_IP + '/r/%s/'
URL_USER = URL_IP + '/r/%s/u/%s/'

# Functions
def _gen_id():
    return ''.join(random.choice(ID_CHARS, ID_LEN))

def gen_anon():
    return 'anon' + ''.join(random.choice(list(string.digits), 5))

def gen_room_name():
    return 'lounge' + ''.join(random.choice(list(string.digits), 5))

def to_ords(text):
    return ' '.join(str(ord(i)) for i in text)

def to_str(ordtext):
    return ''.join([chr(int(i)) for i in ordtext.split()])

def gen_qr(val):
    qr = qrcode.QRCode(version=1, error_correction=qrcode.constants.ERROR_CORRECT_H, box_size=10, border=4)
    qr.add_data(val)
    qr.make(fit=True)
    img = qr.make_image()
    p_qr = _gen_id() + '.jpg'
    img.save(settings.MEDIA_URL + p_qr)
    return p_qr

# Models
class Room(models.Model):
    room_name = models.CharField(max_length=40, default='')
    room_id = models.CharField(max_length=ID_LEN, default=_gen_id, unique=True)
    room_max_size = models.IntegerField(default=0)
    room_owner = models.CharField(max_length=ID_LEN, default='')
    room_qr = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.room_name

    def get_user_ids(self):
        return [u.user_id for u in self.user_set.all()]

    def get_user_names(self, exclude=None):
        names = [u.user_name for u in self.user_set.all()]
        if exclude and exclude in names:
            names.remove(exclude)
        return '\n'.join(names)

    def set_qr(self):
        self.room_qr = gen_qr(URL_ROOM % self.room_id)
        self.save()
        return

    def clean(self):
        self.chat_set.all().delete()
        for u in self.user_set.all():
            u.del_qr()
        self.user_set.all().delete()
        os.remove(settings.MEDIA_URL + self.room_qr)
        return

class User(models.Model):
    room = models.ForeignKey(Room, null=True, on_delete=models.SET_NULL)
    user_name = models.CharField(max_length=100, default='')
    user_id = models.CharField(max_length=ID_LEN, default=_gen_id, unique=True)
    user_phone = models.CharField(max_length=10, default='')
    user_email = models.CharField(max_length=100, default='')
    user_qr = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.user_name

    def set_qr(self):
        self.user_qr = gen_qr(URL_USER % (self.room.room_id, self.user_id))
        self.save()
        return

    def del_qr(self):
        os.remove(settings.MEDIA_URL + self.user_qr)
        return

class Chat(models.Model):
    room = models.ForeignKey(Room, null=True, on_delete=models.SET_NULL)
    chat_id = models.CharField(max_length=ID_LEN, default=_gen_id, unique=True)
    chatter = models.TextField(default='', blank=True)
    user_ids = models.TextField(default='', blank=True)

    def get_user_ids(self):
        if self.user_ids:
            return self.user_ids.split('/')
        else:
            return []

    def get_chatter(self, n=20):
        chats = []
        if self.chatter:
            for x in self.chatter.split(COM_SEP)[-n:]:
                u, c = x.split(COM_UC)
                chats.append(self.make_message(to_str(u), to_str(c)))

        return '\n'.join(chats)

    @staticmethod
    def make_message(user_name, comment):
        return '%s:  %s' % (user_name, comment)

    def add_comment(self, user_name, comment):
        if self.chatter:
            self.chatter += COM_SEP + to_ords(user_name) + COM_UC + to_ords(comment)
        else:
            self.chatter += to_ords(user_name) + COM_UC + to_ords(comment)
        self.save()
        return

loungeman/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Room, gen_anon, gen_room_name, URL_ROOM, URL_USER
from loungeman.lutils.core import messenger, get_keys

_HELM_ID_ = get_keys()['helm_pw']
_STATIC_ROOMS_ = 'loungeman/static/static_rooms'
_srooms = {r.split(':')[0]:r.split(':')[1] for r in open(_STATIC_ROOMS_, 'r').read().strip().split('\n')}

# Create your views here.
def index(request):

    rooms = Room.objects.all()
    context = {'rooms': rooms}

    return render(request, 'loungeman/index.html', context=context)

def helm(request, user_id):

    if user_id != _HELM_ID_:
        return HttpResponseRedirect(reverse('loungeman:index'))

    rooms = Room.objects.all()
    context = {'rooms': rooms}

    return render(request, 'loungeman/helm.html', context=context)

def room_view(request, room_id, user_id=None):

    try:
        r = Room.objects.get(room_id=room_id)
        uname = r.user_set.get(user_id=user_id).user_name if user_id else None
        context = {'room': r, 'uid': user_id, 'uname': uname}
        return render(request, 'loungeman/room.html', context=context)
    except:
        return HttpResponseRedirect(reverse('loungeman:room', args=(_srooms['ERROR'],)))

def adding_user(request, room_id):

    r = Room.objects.get(room_id=room_id)
    user_name = request.POST.get('user_name', '')
    u = r.user_set.create(user_name=user_name if user_name else gen_anon())
    u.set_qr()

    return HttpResponseRedirect(reverse('loungeman:room_user', args=(room_id, u.user_id)))

def adding_room(request):

    room_name = request.POST.get('room_name', '')
    r = Room(room_name=room_name if room_name else gen_room_name())
    r.save()
    r.set_qr()
    r.chat_set.create()
    u = r.user_set.create(user_name='Admin')
    u.set_qr()
    r.room_owner = u.user_id
    r.save()

    return HttpResponseRedirect(reverse('loungeman:room_user', args=(r.room_id, u.user_id)))

def removing_room(request, room_id):

    r = Room.objects.get(room_id=room_id)
    r.clean()
    r.delete()

    return HttpResponseRedirect(reverse('loungeman:helm', args=(_HELM_ID_,)))

def owner_delete_room(request, room_id, user_id):

    r = Room.objects.get(room_id=room_id)
    if r.room_owner == user_id:
        r.clean()
        r.delete()
    else:
        return HttpResponseRedirect(reverse('loungeman:room', args=(room_id,)))

    return HttpResponseRedirect(reverse('loungeman:index'))

def get_qr(request, room_id, user_id=None):

    r = Room.objects.get(room_id=room_id)
    u = r.user_set.get(user_id=user_id) if user_id else None
    p_img = u.user_qr if user_id else r.room_qr

    context = {
        'img': p_img,
        'room': r,
        'user': u,
    }

    return render(request, 'loungeman/getqr.html', context=context)

def send_qr(request, room_id, user_id=None):

    user_name = request.POST.get('user_name', '')
    user_phone = request.POST.get('user_phone', '')
    # user_email = request.POST.get('user_email', '')

    if user_phone and isinstance(user_phone, str) and len(user_phone)==10 and user_phone.isdigit():

        room_name = Room.objects.get(room_id=room_id).room_name

        if user_id:
            msg = "%s, here's your lounge access to %s: %s" % (user_name, room_name, URL_USER % (room_id, user_id))
        else:
            msg = "%s, you've been invited to join lounge %s: %s" % (user_name, room_name, URL_ROOM % room_id)

        messenger(phone=user_phone, msg=msg)

    if not user_id:
        return HttpResponseRedirect(reverse('loungeman:getqr', args=(room_id,)))

    return HttpResponseRedirect(reverse('loungeman:getqr', args=(room_id, user_id)))

loungeman/templates/loungeman/addeduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Loungeon</title>
</head>
<body>
You are added
</body>
</html>

loungeman/templates/loungeman/getqr.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
a.title {
  font-size: 20px;
  font-weight: bold;
  }
.button {
  background-color: white;
  border: none;
  color: gray;
  padding: 6px 18px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  -webkit-transition-duration: 0.2s;
  transition-duration: 0.1s;
  cursor: pointer;
  border-radius: 5px;
  }
.button:hover {
  color: black;
  }
.button:disabled {
  color: red;
  text-decoration: line-through;
  }
.centered {
  position: fixed;
  top: 45%;
  left: 50%;
  transform: translate(-50%, -50%);
  }
.textin {
  background-color: #f1f1f1;
  border: none;
  padding: 5px 12px;
  border-radius: 5px;
}
textarea {resize: none}
</style>

<head>
    <meta charset="UTF-8">
    <title>Loungeon</title>
</head>
<body class="centered">
<a href="{% url 'loungeman:index' %}" rel="noopener noreferrer" target="_blank" style="text-decoration: none">
        <input class="button" type="button" value="L O U N G E O N"></a>
<h2>{{ room.room_name }}</h2>

{% if user %}
<br>
<form action="{% url 'loungeman:sendqr_user' room.room_id user.user_id %}" method="post">
    {% csrf_token %}
    <input class="textin" type="text" name="user_name" placeholder = "name" value="{{ user.user_name }}" size="20"><br><br>
    10-digit US phone number<br>
    <input class="textin" type="text" id="user_phone" name="user_phone" placeholder = "1110009999" value="{{ user.user_phone }}" size="10" maxlength="10" required>
    <input class="button" type="submit" id="user_submit" value="SEND" disabled>
    <script>document.getElementById("user_phone").focus();</script>
</form>

{% else %}
<br>
<form action="{% url 'loungeman:sendqr_room' room.room_id %}" method="post">
    {% csrf_token %}
    <input class="textin" type="text" id="user_name" name="user_name" placeholder = "your name" value="" size="20"><br><br>
    10-digit US phone number<br>
    <input class="textin" type="text" id="phone" name="user_phone" placeholder = "1110009999" value="" size="10" maxlength="10" required>
    <input class="button" type="submit" id="submit" value="SEND" disabled>
    <script>document.getElementById("user_name").focus();</script>
</form>

{% endif %}

<img src="/{{ MEDIA_URL }}{{ img }}" alt="QR" height="200" width="200">

<br><br>(text message rate may apply)<br>

</body>

<script>
{% if user %}
    const uphone = document.getElementById('user_phone');
    const usubmit = document.getElementById('user_submit');
{% else %}
    const uphone = document.getElementById('phone');
    const usubmit = document.getElementById('submit');
{% endif %}
    var phonexp = /^\d{10}$/;
    uphone.addEventListener('keyup', function(event) {
        if ((uphone.value.match(phonexp))) {
            usubmit.disabled = false;
        } else {
            usubmit.disabled = true;
        }
    });
</script>

</html>

loungeman/templates/loungeman/helm.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
a.title {
  font-size: 20px;
  font-weight: bold;
  }
.button {
  background-color: white;
  border: none;
  color: gray;
  padding: 6px 18px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  -webkit-transition-duration: 0.2s;
  transition-duration: 0.1s;
  cursor: pointer;
  border-radius: 5px;
  }
.button:hover {
  color: black;
  }
textarea {resize: none}
</style>

<head>
    <meta charset="UTF-8">
    <title>Loungeon Helm</title>
</head>
<body>
<a href="{% url 'loungeman:index' %}" rel="noopener noreferrer" target="_blank" style="text-decoration: none">
        <input class="button" type="button" value="L O U N G E O N"></a>
<h2>Welcome to the command deck!</h2><br>
<h4>Lounges</h4>
{% if rooms %}
    <ul>
    {% for r in rooms %}
        <li><a href="{% url 'loungeman:room' r.room_id %}">{{ r.room_name }}</a>
            <a href="{% url 'loungeman:removedroom' r.room_id %}" style="text-decoration: none">
                <input type="button" value="Destroy"></a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No room is available.</p>
{% endif %}

<br>
<form action="{% url 'loungeman:addedroom' %}" method="post">
    {% csrf_token %}
    <input type="text" name="room_name" id="room_name" placeholder = "Lounge Name" value="">
    <input type="submit" value="Make Lounge">
</form>
</body>

</body>
</html>

loungeman/templates/loungeman/index.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
.button {
  background-color: Transparent;
  border: none;
  color: #a195ad;
  padding: 5px 18px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 5px;
  }
.button:hover {
  color: black;
  }
.centered {
  position: fixed;
  top: 45%;
  left: 50%;
  transform: translate(-50%, -50%);
  }
.banner {
  background-color: #341651;
  }
.bkg {
  background-image: linear-gradient(to right, #0d3a84, #2d3a4f);
  }
.textin {
  background-color: #e8e8e8;
  border: none;
  padding: 8px 16px;
  border-radius: 5px;
}
</style>
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loungeon</title>
</head>

<body class="bkg">
<div class="banner">
    <a href="{% url 'loungeman:index' %}" rel="noopener noreferrer" target="_blank" style="text-decoration: none">
        <input class="button" type="button" value="L O U N G E O N"></a>
</div>
<div>
    <div class="centered">
        <h2 style="color: white">Create Your Lounge</h2>

        <br>
        <form action="{% url 'loungeman:addedroom' %}" method="post">
            {% csrf_token %}
            <input class="textin" type="text" name="room_name" id="room_name" placeholder = "Lounge Name (optional)" value="" size="30">
            <input class="button" type="submit" value="Create">
        </form>
    </div>
</div>
</body>

<script>document.getElementById("room_name").focus();</script>

</html>

loungeman/templates/loungeman/room.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif;}
html, body {height: 100%}
.title {
  color: #d4c9d8;
  font-size: 20px;
  font-weight: bold;
  }
.text1 {
  color: #d4c9d8;
  font-size: 20px;
  font-weight: bold;
  }
.text2 {
  color: #d4c9d8;
  font-size: 16px;
  }
.button {
  background-color: Transparent;
  border: none;
  color: #a195ad;
  padding: 5px 18px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  -webkit-transition-duration: 0.2s;
  transition-duration: 0.1s;
  cursor: pointer;
  border-radius: 5px;
  }
.button:hover {
  color: white;
  }
.box {
  display: flex;
  flex-flow: column;
  height: 100%;
  }
.box .banner {
  background-color: #341651;
  flex: 0 1 auto;
  }
.box .content {
  flex: 1 1 auto;
  overflow-y: auto;
  }
.box .comment {
  flex: 0 1 auto;
  padding: 10px 0px;
  }
.bkg {
  height: 100%;
  background-image: linear-gradient(to right, #520e6d, #1b0f6d);
  }
textarea {
  resize: none;
  border: none;
  padding: 5px 12px;
  background-color: Transparent;
  }
.textin {
  background-color: #f1f1f1;
  border: none;
  padding: 5px 12px;
  border-radius: 5px;
}
.overlay {
  position: fixed;
  display: none;
  background-color: #6f6f6f;
  z-index: 2;
  cursor: pointer;
  border-radius: 5px;
  border: 2px solid #dfdfdf;
  opacity: 0.8;
}
.msg_container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}
.w3-sidebar {background-color: #091e42!important; opacity:0.9}
.w3-button {color: #97a7c4!important}
.w3-button:hover {background-color: Transparent!important; color: white!important}
</style>

<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loungeon - {{ room.room_name }}</title>
</head>

<body class="bkg">
<div class="box">
    <div class="banner">
        <a href="{% url 'loungeman:index' %}" rel="noopener noreferrer" target="_blank" style="text-decoration: none">
            <input class="button" type="button" value="L O U N G E O N"></a>
    </div>

    <div id="sidebar" class="w3-sidebar w3-bar-block w3-card w3-animate-left" style="display:none">
        <button class="w3-bar-item w3-button w3-large fas fa-chevron-left" onclick="nav_click()"></button>
        <a class="w3-bar-item w3-button w3-large" href="{% url 'loungeman:getqr' room.room_id %}" rel="noopener noreferrer" target="_blank" style="text-decoration: none">
            Share</a>
        <button class="w3-bar-item w3-button w3-large" onclick="guest_click()">Guests</button>
        <button class="w3-bar-item w3-button w3-large" onclick="bot_click()">Bots</button>
        {% if uid %}
        <a class="w3-bar-item w3-button w3-large" href="{% url 'loungeman:getqr' room.room_id uid %}" rel="noopener noreferrer" target="_blank" style="text-decoration: none">
            Save</a>
            {% if room.room_owner == uid %}
        <a class="w3-bar-item w3-button w3-large" href="{% url 'loungeman:room' room.room_id %}" rel="noopener noreferrer" target="_blank" style="text-decoration: none">
            Pop Out</a>
        <br><br><br><br><a class="w3-bar-item w3-button w3-large" href="{% url 'loungeman:delroom' room.room_id uid %}" style="text-decoration: none">
            Destroy</a>
            {% else %}
        <button class="w3-bar-item w3-button w3-large" id="leave">Leave</button>
            {% endif %}
        {% endif %}
    </div>

    <div class="w3-sidebar w3-bar-block w3-card w3-animate-left" id="guestbar" onclick="guest_click()" style="display:none">
        <textarea id="userlog" cols="35" rows="10" autocomplete="off" style="color:#f1f1f1;" readonly></textarea>
    </div>

    <div class="w3-sidebar w3-bar-block w3-card w3-animate-left" id="botbar" onclick="bot_click()" style="display:none">
        <textarea id="bots" cols="35" rows="1" autocomplete="off" style="color:#f1f1f1;" readonly>None</textarea>
    </div>

    <div><button id="openNav" class="w3-button w3-xlarge title" onclick="nav_click()">&#9776; {{ room.room_name }}</button></div>
    <div id="main" class="w3-center content">
        <!--<textarea class="text2 content" id="chatlog" autocomplete="off" style="width: 100%; height: 100%" readonly></textarea>-->
    </div>

    <div class="comment w3-center">
        {% if uid %}
        <div class="w3-thrid w3-row">
            <span class="text1" style="font-weight:bold">{{ uname }}</span>
        </div>

        <br>
        <div style="width:100%; display:table">
            <input class="textin" id="comment" type="text" style="display:table-cell; width:80%" placeholder="say what?">
            <button class="fas fa-paper-plane w3-button w3-xlarge" id="send"></button>
        </div>

        {% else %}
        <br>
        <form action="{% url 'loungeman:added' room.room_id %}" method="post">
            {% csrf_token %}
            <input class="textin w3-rest" type="text" name="user_name" id="user_name" placeholder = "your name (optional)" value="">
            <button class="fas fa-plus-circle w3-button w3-xlarge" id="adduser" type="submit"></button>
        </form>

        {% endif %}
    </div>
</div>
</body>

{% if uid %}
<script>
    var urlroom='r/{{ room.room_id }}/';
    var url0='r/{{ room.room_id }}/u/{{ uid }}/';
    var userid='{{ uid }}';
    document.getElementById("comment").focus();
</script>
{% else %}
<script>
    var url0='r/{{ room.room_id }}/';
    var userid='';
    document.getElementById("user_name").focus();
</script>
{% endif %}

{% load static %}
<script type="text/javascript" src="{% static 'js/chatws.js' %}"></script>
<script>
function nav_click() {
  if (document.getElementById("sidebar").style.display == "block") {
    document.getElementById("sidebar").style.display = "none";
  } else {
    document.getElementById("sidebar").style.display = "block";
  }
}
function guest_click() {
  if (document.getElementById("guestbar").style.display == "block") {
    document.getElementById("guestbar").style.display = "none";
  } else {
    document.getElementById("guestbar").style.display = "block";
  }
}
function bot_click() {
  if (document.getElementById("botbar").style.display == "block") {
    document.getElementById("botbar").style.display = "none";
  } else {
    document.getElementById("botbar").style.display = "block";
  }
}
</script>

</html>